apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-envs
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          dev: 'true'
      values:
        path: dev
  - clusters:
      selector:
        matchLabels:
          prod: 'true'
      values:
        path: prod
  template:
    metadata:
      name: 'guestbook-{{values.path}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/nikita-akuity/guestbook-delivery.git
        targetRevision: HEAD
        path: 'env/{{values.path}}'
      destination:
        server: '{{server}}'
        namespace: 'guestbook-{{values.path}}'
      syncPolicy:
        syncOptions:
        - createNamespace=true
